{
  "distThreshold": 60,
  "distMax": 80,
  "distReload": 50,
  "distIgnore": 0,
  "mainElement": "body",
  "triggerElement": "body",
  "ptrElement": ".ptr",
  "classPrefix": "ptr--",
  "cssProp": "min-height",
  "iconArrow": "&#8675;",
  "iconRefreshing": "&hellip;",
  "instructionsPullToRefresh": "Pull down to refresh",
  "instructionsReleaseToRefresh": "Release to refresh",
  "instructionsRefreshing": "Refreshing",
  "refreshTimeout": 500,
  "getMarkup": "<div class=\"__PREFIX__box\"><div class=\"__PREFIX__content\"><div class=\"__PREFIX__icon\"></div><div class=\"__PREFIX__text\"></div></div></div>",
  "getStyles": ".__PREFIX__ptr { box-shadow: inset 0 -3px 5px rgba(0, 0, 0, 0.12); pointer-events: none; font-size: 0.85em; font-weight: bold; top: 0; height: 0; transition: height 0.3s, min-height 0.3s; text-align: center; width: 100%; overflow: hidden; display: flex; align-items: flex-end; align-content: stretch; } .__PREFIX__box { padding: 10px; flex-basis: 100%; } .__PREFIX__pull { transition: none; } .__PREFIX__text { margin-top: .33em; color: rgba(0, 0, 0, 0.3); } .__PREFIX__icon { color: rgba(0, 0, 0, 0.3); transition: transform .3s; } .__PREFIX__top { touch-action: pan-x pan-down pinch-zoom; } .__PREFIX__release .__PREFIX__icon { transform: rotate(180deg); }",
  "onInit": "function() {}",
  "onRefresh": "function() { location.reload(); }",
  "resistanceFunction": "function(t) { return Math.min(1, t / 2.5); }",
  "shouldPullToRefresh": "function() { return !window.scrollY; }"
      }
